CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL,
    time_spent INTEGER NOT NULL,
    start DATETIME,
    end DATETIME DEFAULT CURRENT_TIMESTAMP
);
