version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile  # Use the custom Dockerfile
    container_name: time-tracker-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: time_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data
volumes:
  pgdata:

