version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      VITE_APP_PASSWORD: ${VITE_APP_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    container_name: time-tracker-app
    depends_on:
      - postgres
    ports:
    - "5173:5173"

  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: time-tracker-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data

volumes:
  pgdata:

