version: '3.8'
services:
  app:
    build:
      context: .
      target: app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      LOCAL_DEV: ${LOCAL_DEV}
    container_name: time-tracker-app
    depends_on:
      - db
    ports:
    - "5173:5173"

  db:
    build:
      context: .
      target: db
    container_name: time-tracker-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data  # Persist data

